// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using interest_web_api.Data;

#nullable disable

namespace interest_web_api.Migrations
{
    [DbContext(typeof(InterestDbContext))]
    partial class InterestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("interest_rates_schema")
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("interest_web_api.Models.CorporationInterest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("OverMillion")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Period")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.Property<double>("UpToMillion")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CorporationInterestTable", "interest_rates_schema");
                });

            modelBuilder.Entity("interest_web_api.Models.HouseholdInterest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("ForConsumption")
                        .HasColumnType("double precision");

                    b.Property<double>("ForHousePurchase")
                        .HasColumnType("double precision");

                    b.Property<double>("ForOtherPurposes")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Period")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("HouseholdInterestTable", "interest_rates_schema");
                });
#pragma warning restore 612, 618
        }
    }
}
